//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSiftTests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class MockAPIResponses : global::System.Configuration.ApplicationSettingsBase {
        
        private static MockAPIResponses defaultInstance = ((MockAPIResponses)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MockAPIResponses())));
        
        public static MockAPIResponses Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"created_at\":\"2011-05-12 11:18:07\",\r\n    \"dpu\":\"0.1\"\r\n}")]
        public string Validate {
            get {
                return ((string)(this["Validate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"hash\": \"9fe133a7ee1bd2757f1e26bd78342458\",\r\n    \"created_at\": \"2011-05-12" +
            " 11:18:07\",\r\n    \"dpu\": \"0.1\"\r\n}")]
        public string Compile {
            get {
                return ((string)(this["Compile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
   ""start"": ""Mon, 07 Nov 2011 11:15:00 +0000"",
   ""end"": ""Mon, 07 Nov 2011 12:15:00 +0000"",
   ""streams"": {
       ""693f5134c73a62ed85ef271040bf266b"": {
            ""licenses"": {
                ""facebook"":365,
                ""twitter"":18062
            },
            ""seconds"": 3600
       },
       ""14af4134c73a62ed65ef1f1040bf321e"": {
            ""licenses"": {
                ""facebook"":344,
                ""twitter"":26062
            },
            ""seconds"": 3900
       }
   }
}")]
        public string Usage {
            get {
                return ((string)(this["Usage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
   ""dpu"": 0.2,
   ""detail"": {
       ""contains"": {
           ""count"": 2,
           ""dpu"": 0.2,
           ""targets"": {
               ""interaction.content"": {
                   ""count"": 1,
                   ""dpu"": 0.1
               },
               ""interaction.title"": {
                   ""count"": 1,
                   ""dpu"": 0.1
               }
           }
       }
   }
}")]
        public string DPU {
            get {
                return ((string)(this["DPU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n   \"balance\": {\r\n     \"plan\": \"Platinum\",\r\n     \"cost\": 0,\r\n     \"remaining_dp" +
            "us\": 249993.7\r\n   }\r\n}")]
        public string Balance {
            get {
                return ((string)(this["Balance"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""data"": [
        {
            ""id"": ""6b42f539793a02bfd68c"",
            ""definition_id"": ""6beacf0faeb77c974ab801733ed2c597"",
            ""name"": ""twitter"",
            ""start"": 1274742000,
            ""end"": 1339110000,
            ""created_at"": 1339147632,
            ""status"": ""init"",
            ""progress"": 0,
            ""sources"": [
                ""facebook"",
                ""twitter""
            ],
            ""sample"": 100
        },
        {
            ""id"": ""fdf6652ac82206358eab"",
            ""definition_id"": ""93558e17de15072fa126370c37c5bd8f"",
            ""name"": ""test"",
            ""start"": 1337040000,
            ""end"": 1337126400,
            ""created_at"": 1337161927,
            ""status"": ""succeeded"",
            ""progress"": 100,
            ""sources"": [
                """"
            ],
            ""sample"": 100
        }
    ],
    ""count"": 79
}")]
        public string HistoricsGet {
            get {
                return ((string)(this["HistoricsGet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""dpus"": 234.6916666667,
    ""id"": ""4ef7c852a96d6352764f"",
    ""availability"": {
        ""start"": 1341673200,
        ""end"": 1341759600,
        ""sources"": {
            ""twitter"": {
                ""status"": 99,
                ""versions"": [
                    3
                ],
                ""augmentations"": {
                    ""klout"": 50,
                    ""links"": 100
                }
            },
            ""facebook"": {
                ""status"": 99,
                ""versions"": [
                    2,
                    3
                ],
                ""augmentations"": {
                    ""links"": 95
                }
            }
        }
    }
}")]
        public string HistoricsPrepare {
            get {
                return ((string)(this["HistoricsPrepare"]));
            }
        }
    }
}
