//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSiftTests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class MockAPIResponses : global::System.Configuration.ApplicationSettingsBase {
        
        private static MockAPIResponses defaultInstance = ((MockAPIResponses)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MockAPIResponses())));
        
        public static MockAPIResponses Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"created_at\":\"2011-05-12 11:18:07\",\r\n    \"dpu\":\"0.1\"\r\n}")]
        public string Validate {
            get {
                return ((string)(this["Validate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"hash\": \"9fe133a7ee1bd2757f1e26bd78342458\",\r\n    \"created_at\": \"2011-05-12" +
            " 11:18:07\",\r\n    \"dpu\": \"0.1\"\r\n}")]
        public string Compile {
            get {
                return ((string)(this["Compile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
   ""start"": ""Mon, 07 Nov 2011 11:15:00 +0000"",
   ""end"": ""Mon, 07 Nov 2011 12:15:00 +0000"",
   ""streams"": {
       ""693f5134c73a62ed85ef271040bf266b"": {
            ""licenses"": {
                ""facebook"":365,
                ""twitter"":18062
            },
            ""seconds"": 3600
       },
       ""14af4134c73a62ed65ef1f1040bf321e"": {
            ""licenses"": {
                ""facebook"":344,
                ""twitter"":26062
            },
            ""seconds"": 3900
       }
   }
}")]
        public string Usage {
            get {
                return ((string)(this["Usage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
   ""dpu"": 0.2,
   ""detail"": {
       ""contains"": {
           ""count"": 2,
           ""dpu"": 0.2,
           ""targets"": {
               ""interaction.content"": {
                   ""count"": 1,
                   ""dpu"": 0.1
               },
               ""interaction.title"": {
                   ""count"": 1,
                   ""dpu"": 0.1
               }
           }
       }
   }
}")]
        public string DPU {
            get {
                return ((string)(this["DPU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n   \"balance\": {\r\n     \"plan\": \"Platinum\",\r\n     \"cost\": 0,\r\n     \"remaining_dp" +
            "us\": 249993.7\r\n   }\r\n}")]
        public string Balance {
            get {
                return ((string)(this["Balance"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""data"": [
        {
            ""id"": ""6b42f539793a02bfd68c"",
            ""definition_id"": ""6beacf0faeb77c974ab801733ed2c597"",
            ""name"": ""twitter"",
            ""start"": 1274742000,
            ""end"": 1339110000,
            ""created_at"": 1339147632,
            ""status"": ""init"",
            ""progress"": 0,
            ""sources"": [
                ""facebook"",
                ""twitter""
            ],
            ""sample"": 100
        },
        {
            ""id"": ""fdf6652ac82206358eab"",
            ""definition_id"": ""93558e17de15072fa126370c37c5bd8f"",
            ""name"": ""test"",
            ""start"": 1337040000,
            ""end"": 1337126400,
            ""created_at"": 1337161927,
            ""status"": ""succeeded"",
            ""progress"": 100,
            ""sources"": [
                """"
            ],
            ""sample"": 100
        }
    ],
    ""count"": 79
}")]
        public string HistoricsGet {
            get {
                return ((string)(this["HistoricsGet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""dpus"": 234.6916666667,
    ""id"": ""4ef7c852a96d6352764f"",
    ""availability"": {
        ""start"": 1341673200,
        ""end"": 1341759600,
        ""sources"": {
            ""twitter"": {
                ""status"": 99,
                ""versions"": [
                    3
                ],
                ""augmentations"": {
                    ""klout"": 50,
                    ""links"": 100
                }
            },
            ""facebook"": {
                ""status"": 99,
                ""versions"": [
                    2,
                    3
                ],
                ""augmentations"": {
                    ""links"": 95
                }
            }
        }
    }
}")]
        public string HistoricsPrepare {
            get {
                return ((string)(this["HistoricsPrepare"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""id"": ""9e97d9ac115e58fcb7ab"",
    ""definition_id"": ""e4d0b9bb266e8f3f2de405f6c1a2de23"",
    ""name"": ""historics-get-test"",
    ""start"": 1325376001,
    ""end"": 1325894401,
    ""created_at"": 1363271961,
    ""status"": ""running"",
    ""progress"": 15,
    ""sources"": [
        ""twitter""
    ],
    ""sample"": 100,
    ""chunks"": [
        {
            ""status"": ""succeeded"",
            ""progress"": 100,
            ""start_time"": 1325376001,
            ""end_time"": 1325462400
        },
        {
            ""status"": ""running"",
            ""progress"": 5,
            ""start_time"": 1325462400,
            ""end_time"": 1325548800
        },
        {
            ""status"": ""init"",
            ""progress"": 0,
            ""start_time"": 1325548800,
            ""end_time"": 1325635200
        },
        {
            ""status"": ""init"",
            ""progress"": 0,
            ""start_time"": 1325635200,
            ""end_time"": 1325721600
        },
        {
            ""status"": ""init"",
            ""progress"": 0,
            ""start_time"": 1325721600,
            ""end_time"": 1325808000
        },
        {
            ""status"": ""init"",
            ""progress"": 0,
            ""start_time"": 1325808000,
            ""end_time"": 1325894400
        },
        {
            ""status"": ""init"",
            ""progress"": 0,
            ""start_time"": 1325894400,
            ""end_time"": 1325894401
        }
    ]
}")]
        public string HistoricsGetById {
            get {
                return ((string)(this["HistoricsGetById"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""data"": [
        {
            ""id"": ""6b42f539793a02bfd68c"",
            ""definition_id"": ""6beacf0faeb77c974ab801733ed2c597"",
            ""name"": ""twitter"",
            ""start"": 1274742000,
            ""end"": 1339110000,
            ""created_at"": 1339147632,
            ""status"": ""init"",
            ""progress"": 0,
            ""sources"": [
                ""facebook"",
                ""twitter""
            ],
            ""sample"": 100
        }
    ],
    ""count"": 79
}")]
        public string HistoricsGetMax1 {
            get {
                return ((string)(this["HistoricsGetMax1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"id\": \"9e97d9ac115e58fcb7ab\",\r\n    \"definition_id\": \"cdd0b9bb266e8f3f2de40" +
            "5f6c1a2b23e\",\r\n    \"name\": \"job-estimation-test\",\r\n    \"start\": 1325376001,\r\n   " +
            " \"end\": 1325894401,\r\n    \"created_at\": 1363271961,\r\n    \"status\": \"running\",\r\n  " +
            "  \"progress\": 15,\r\n    \"sources\": [\r\n        \"twitter\"\r\n    ],\r\n    \"sample\": 10" +
            "0,\r\n    \"volume_info\": {\r\n        \"twitter\": 1448591013\r\n    },\r\n    \"chunks\": [" +
            "\r\n        {\r\n            \"status\": \"succeeded\",\r\n            \"progress\": 100,\r\n " +
            "           \"start_time\": 1325376001,\r\n            \"end_time\": 1325462400,\r\n     " +
            "       \"estimated_completion\": 1363274434\r\n        },\r\n        {\r\n            \"s" +
            "tatus\": \"running\",\r\n            \"progress\": 5,\r\n            \"start_time\": 132546" +
            "2400,\r\n            \"end_time\": 1325548800,\r\n            \"estimated_completion\": " +
            "1363277434\r\n        },\r\n        {\r\n            \"status\": \"init\",\r\n            \"p" +
            "rogress\": 0,\r\n            \"start_time\": 1325548800,\r\n            \"end_time\": 132" +
            "5635200,\r\n            \"estimated_completion\": 1363285834\r\n        },\r\n        {\r" +
            "\n            \"status\": \"init\",\r\n            \"progress\": 0,\r\n            \"start_t" +
            "ime\": 1325635200,\r\n            \"end_time\": 1325721600,\r\n            \"estimated_c" +
            "ompletion\": 1363279834\r\n        },\r\n        {\r\n            \"status\": \"init\",\r\n  " +
            "          \"progress\": 0,\r\n            \"start_time\": 1325721600,\r\n            \"en" +
            "d_time\": 1325808000,\r\n            \"estimated_completion\": 1363282234\r\n        }," +
            "\r\n        {\r\n            \"status\": \"init\",\r\n            \"progress\": 0,\r\n        " +
            "    \"start_time\": 1325808000,\r\n            \"end_time\": 1325894400,\r\n            " +
            "\"estimated_completion\": 1363284034\r\n        },\r\n        {\r\n            \"status\":" +
            " \"init\",\r\n            \"progress\": 0,\r\n            \"start_time\": 1325894400,\r\n   " +
            "         \"end_time\": 1325894401,\r\n            \"estimated_completion\": 1363287634" +
            "\r\n        }\r\n    ],\r\n    \"estimated_completion\": 1363287634\r\n}")]
        public string HistoricsGetWithCompletion {
            get {
                return ((string)(this["HistoricsGetWithCompletion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[
    {
        ""start"": ""1325376000"",
        ""end"": 1325462400,
        ""sources"": {
            ""twitter"": {
                ""augmentations"": {
                    ""demographic"": 100,
                    ""klout"": 100,
                    ""language"": 100,
                    ""links"": 100,
                    ""salience"": 100,
                    ""trends"": 100
                },
                ""versions"": [
                    ""1""
                ],
                ""status"": 100
            }
        }
    },
    {
        ""start"": ""1325462400"",
        ""end"": 1325548800,
        ""sources"": {
            ""twitter"": {
                ""augmentations"": {
                    ""demographic"": 100,
                    ""klout"": 100,
                    ""language"": 100,
                    ""links"": 100,
                    ""salience"": 100,
                    ""trends"": 100
                },
                ""versions"": [
                    ""1""
                ],
                ""status"": 100
            }
        }
    }
]")]
        public string HistoricsStatus {
            get {
                return ((string)(this["HistoricsStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""count"": 2,
    ""subscriptions"": [
        {
            ""id"": ""d668655cfe5f93741ddcd30bb309a8c7"",
            ""output_type"": ""dynamodb"",
            ""name"": ""mypushsubscription1"",
            ""created_at"": 1365430066,
            ""hash"": ""42d388f8b1db997faaf7dab487f11290"",
            ""hash_type"": ""stream"",
            ""output_params"": {
                ""table"": ""datasift-dynamodb"",
                ""region"": ""dynamodb.eu-west-1.amazonaws.com""
            },
            ""status"": ""active"",
            ""last_request"": null,
            ""last_success"": null,
            ""remaining_bytes"": null,
            ""lost_data"": false,
            ""start"": 0,
            ""end"": 0
        },
        {
            ""id"": ""d468655cfe5f93741ddcd30bb309a8c7"",
            ""output_type"": ""dynamodb"",
            ""name"": ""mypushsubscription2"",
            ""created_at"": 1365430066,
            ""hash"": ""42d388f8b1db997faaf7dab487f11290"",
            ""hash_type"": ""stream"",
            ""output_params"": {
                ""table"": ""datasift-dynamodb"",
                ""region"": ""dynamodb.eu-west-1.amazonaws.com""
            },
            ""status"": ""active"",
            ""last_request"": null,
            ""last_success"": null,
            ""remaining_bytes"": null,
            ""lost_data"": false,
            ""start"": 0,
            ""end"": 0
        }
    ]
}")]
        public string PushGet {
            get {
                return ((string)(this["PushGet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""id"": ""d468655cfe5f93741ddcd30bb309a8c7"",
    ""output_type"": ""dynamodb"",
    ""name"": ""mypushsubscription1"",
    ""created_at"": 1365430066,
    ""hash"": ""42d388f8b1db997faaf7dab487f11290"",
    ""hash_type"": ""stream"",
    ""output_params"": {
        ""table"": ""datasift-dynamodb"",
        ""region"": ""dynamodb.eu-west-1.amazonaws.com""
    },
    ""status"": ""active"",
    ""last_request"": null,
    ""last_success"": null,
    ""remaining_bytes"": null,
    ""lost_data"": false,
    ""start"": 0,
    ""end"": 0
}")]
        public string PushGetById {
            get {
                return ((string)(this["PushGetById"]));
            }
        }
    }
}
